- lib/bone.js
- lib/spell.js
- test/test.spell.js
> fix: append default scope when declaring relations

- CONTRIBUTING.md
- lib/drivers/postgres/index.js
- lib/drivers/sqlite/index.js
- package.json
- test/start.sh
- test/unit/drivers/test.mysql.js
- test/unit/drivers/test.postgres.js
- test/unit/drivers/test.sqlite.js
- how to get started
- wip: how the code is organized
> docs: contributing guide

- History.md
- Readme.md
- docs/basics.md
- docs/zh/basics.md
- index.js
- lib/adapters/sequelize.js
- lib/bone.js
- lib/connect.js
- lib/data_types.js
- lib/drivers/abstract/index.js
- lib/drivers/abstract/spellbook.js
- lib/drivers/index.js
- lib/drivers/mysql/index.js
- lib/drivers/postgres/index.js
- lib/drivers/postgres/spellbook.js
- lib/drivers/sqlite/index.js
- lib/spell.js
- lib/utils/invokable.js
- package.json
- test/integration/suite/data_types.js
- test/integration/suite/definitions.js
- test/integration/suite/index.js
- test/integration/test.sqlite.js
- test/models/Readme.md
- test/unit/adapters/test.sequelize.js
- test/unit/drivers/test.mysql.js
- test/unit/drivers/test.sqlite.js
- test/unit/test.connect.js
- test/unit/test.realm.js
- test/unit/test.spell.js
> feat: SQLite change column support etc.

- CONTRIBUTING.md
- lib/adapters/sequelize.js
- lib/bone.js
- lib/connect.js
- lib/drivers/abstract/index.js
- lib/drivers/mysql/index.js
- lib/drivers/postgres/index.js
- lib/drivers/sqlite/index.js
- lib/spell.js
- lib/utils/invokable.js
- package.json
- test/integration/suite/basics.js
- test/integration/suite/data_types.js
- test/integration/suite/definitions.js
- test/integration/suite/migrations.js
- test/unit/drivers/test.sqlite.js
- test/unit/test.realm.js
- test/unit/test.spell.js
also refactored
- attribute types (type, dataType, and jsType)
- `{function|Object}` opts.logger
> feat: enhance sequelize shim

- lib/adapters/sequelize.js
- lib/bone.js
- lib/collection.js
- lib/drivers/abstract/index.js
- lib/drivers/abstract/spellbook.js
- lib/drivers/mysql/index.js
- lib/drivers/postgres/index.js
- lib/drivers/sqlite/index.js
- lib/spell.js
- package.json
- test/integration/suite/definitions.js
- test/unit/adapters/test.sequelize.js
- test/unit/drivers/test.sqlite.js
also changed:
- private api: `Model.createSpell()` => `new Spell(Model)`
> feat: renameColumn, removeColumn, and renameTable

- lib/bone.js
- lib/drivers/abstract/index.js
- lib/drivers/mysql/index.js
- lib/drivers/postgres/index.js
- lib/drivers/sqlite/index.js
- test/integration/suite/data_types.js
- test/integration/suite/definitions.js
> fix: SQLite date value replacements

- lib/drivers/abstract/index.js
- lib/drivers/sqlite/index.js
- package.json
- test/integration/suite/data_types.js
- test/unit/drivers/test.sqlite.js
> fix: date/time/datetime/timestamp, a temporary fix

- lib/drivers/abstract/definition.js
- lib/drivers/abstract/logger.js
- lib/drivers/abstract/schema.js
- lib/drivers/mysql/schema.js
- lib/drivers/postgres/definition.js
- lib/drivers/postgres/schema.js
- lib/drivers/sqlite/schema.js
- lib/migrations.js
- lib/spell.js
- test/integration/suite/definitions.js
- test/integration/suite/migrations.js
- test/start.sh
- test/unit/drivers/abstract/test.logger.js
added more test cases to increase api coverage (still incomplete though)
> feat: logger.logMigration & rollback()

- index.js
- lib/bone.js
- lib/data_types.js
- lib/drivers/abstract/definition.js
- lib/drivers/mysql/data_types.js
- lib/drivers/mysql/definition.js
- lib/drivers/mysql/schema.js
- lib/drivers/postgres/data_types.js
- lib/drivers/postgres/definition.js
- lib/drivers/postgres/schema.js
- lib/drivers/sqlite/data_types.js
- lib/drivers/sqlite/definition.js
- lib/drivers/sqlite/schema.js
- test/integration/suite/data_types.js
- test/integration/suite/definitions.js
- test/integration/test.sqlite.js
- test/unit/test.data_types.js
> refactor: subclassing data types to enhance timestamp support

- lib/data_types.js
- lib/expr.js
- test/unit/adapters/test.sequelize.js
- test/unit/test.expr.js
> fix: open ended string could cause infinite loop

- lib/drivers/abstract/spellbook.js
- lib/drivers/mysql/spellbook.js
- test/dumpfile.sql
- test/integration/suite/basics.js
- test/prepare.sh
- test/unit/test.spell.js
> fix: upsert should not touch createdAt if update branch were chosen

- lib/adapters/sequelize.js
- lib/bone.js
- lib/drivers/abstract/spellbook.js
- lib/spell.js
- test/integration/suite/basics.js
- test/models/book.js
- test/unit/adapters/test.sequelize.js
- test/unit/test.expr.js
- test/unit/test.spell.js
> feat: increment/decrement & find({ group }) adapter

- History.md
- lib/drivers/abstract/attribute.js
- lib/drivers/abstract/schema.js
- lib/drivers/mysql/schema.js
- test/integration/suite/basics.js
- test/integration/suite/definitions.js
- test/models/book.js
> feat: driver.addIndex & driver.removeIndex

- History.md
- index.js
- lib/bone.js
- lib/drivers/index.js
- lib/spell.js
- package.json
- test/integration/test.postgres.js
- test/integration/test.sqlite.js
- test/unit/adapters/test.sequelize.js
- test/unit/test.connect.js
- test/unit/test.realm.js
- test/unit/test.spell.js
also updated error messages a bit to better align with JavaScript convention
closes #33
> fix: opts.sequelize, opts.dialect, and opts.client

- lib/drivers/abstract/logger.js
- lib/drivers/mysql/index.js
- lib/drivers/postgres/index.js
- lib/drivers/sqlite/index.js
- test/integration/suite/index.js
- test/unit/drivers/test.mysql.js
- test/unit/drivers/test.postgres.js
- test/unit/drivers/test.sqlite.js
also enhanced logger.logQuery() with duration 
closes #35
> feat: logger.logQueryError()

- lib/adapters/sequelize.js
- lib/drivers/sqlite/schema.js
- test/integration/suite/definitions.js
- test/unit/adapters/test.sequelize.js
- test/unit/test.spell.js
> fix: columns should be added once a time in SQLite

- .github/workflows/nodejs.yml
- test/integration/test.mysql.js
- test/integration/test.mysql2.js
- test/prepare.sh
- test/unit/drivers/test.mysql.js
- test/unit/test.connect.js
- test/unit/test.realm.js
- test/unit/test.spell.js
> build: enable mysql service

- lib/adapters/sequelize.js
- lib/spell.js
- test/unit/adapters/test.sequelize.js
- test/unit/test.spell.js
enhanced following static methods on Model:
- Model.build()
- Model.count()
- Model.min()
- Model.max()
- Model.sum()
also added `.finally()` and `.nodeify()` for better integration with project at hand
> feat: enhance sequelize adapter & .nodeify() support

- History.md
- package.json
* Feat: JSON and JSONB data types
* Feat: support `stringifyObjects` option for mysql client
* Feat: aggregate functions for sequelize adapter
* Feat: `Spell.prototype.nodeify()`
> release: v1.1.0

- lib/bone.js
- lib/drivers/abstract/logger.js
- lib/drivers/mysql/index.js
- lib/drivers/postgres/index.js
- lib/drivers/sqlite/index.js
> feat: logger.logQuery and logger.logQueryError transport  more props

- index.js
- lib/bone.js
- test/unit/test.realm.js
Enable realm.transaction and realm.query
> feat: realm.transaction and realm.query

- test/unit/test.realm.js
> ci: fix github workflow job parallel cause transaction unit test failed

- History.md
- lib/bone.js
- package.json
- test/unit/test.realm.js
> release: v1.2.0

- lib/bone.js
- test/dumpfile.sql
- test/integration/suite/basics.test.js
- test/models/user.js
set defaultValue when create or bulkCreate
> fix: set default values

- lib/bone.js
- lib/drivers/postgres/attribute.js
- lib/drivers/postgres/schema.js
- lib/drivers/sqlite/data_types.js
- lib/drivers/sqlite/schema.js
- test/integration/sqlite.test.js
- test/integration/suite/data_types.test.js
- test/integration/suite/definitions.test.js
- test/unit/connect.test.js
- test/unit/drivers/postgres.test.js
- test/unit/drivers/sqlite.test.js
Model.init() add primaryKey automatically
> feat: init add primaryKey automatically

- index.js
- lib/bone.js
- test/dumpfile.sql
- test/integration/suite/basics.test.js
- test/models/user.js
> feat: init with descriptors

- lib/adapters/sequelize.js
- lib/bone.js
- test/unit/adapters/sequelize.test.js
> fix: sequelize mode isNewRecord

- index.js
- lib/adapters/sequelize.js
- lib/bone.js
- lib/spell.js
- test/dumpfile.sql
- test/unit/adapters/sequelize.test.js
- test/unit/spell.test.js
> fix: soft delete

- lib/adapters/sequelize.js
- lib/bone.js
- test/dumpfile.sql
- test/integration/suite/basics.test.js
- test/models/user.js
- test/unit/adapters/sequelize.test.js
- test/unit/spell.test.js
> feat: [sequelize]support to set setterMethods and getterMethods in  sequelize mode

- lib/adapters/sequelize.js
- lib/bone.js
- test/integration/suite/basics.test.js
- test/unit/adapters/sequelize.test.js
sequelize.changed(key) is compare current dataValues to _previousDataValues
> fix: sequelize mode changed and previous

- lib/drivers/abstract/spellbook.js
- lib/spell.js
- test/unit/expr.test.js
- test/unit/spell.test.js
> fix: order by field() or find_in_set()

- .eslintrc
- lib/bone.js
- lib/drivers/abstract/index.js
- package.json
- test/integration/suite/basics.test.js
- test/unit/drivers/abstract/index.test.js
... which seems a little refactor on changed(name) is necessary
- https://www.yuque.com/leoric/guide/dirty
> refactor: replace attributeChanged() with changed()

- lib/bone.js
- test/integration/suite/basics.test.js
```js
bone.hasAttribute(key)
Bone.hasAttribute(key)
```
> feat: hasAttribute

- .gitignore
- docs/basics.md
- docs/zh/basics.md
- lib/data_types.js
- test/unit/data_types.test.js
Reading schema from exists MySQL Table
> feat: compatible with mysql longtext conversion

- index.js
- lib/drivers/abstract/spellbook.js
- lib/drivers/mysql/spellbook.js
- lib/spell.js
- test/models/user.js
- test/unit/spell.test.js
> [FEAT] support raw sql

- lib/adapters/sequelize.js
- lib/bone.js
- lib/drivers/abstract/schema.js
- lib/drivers/postgres/attribute.js
- lib/drivers/postgres/schema.js
- lib/drivers/sqlite/schema.js
- test/integration/suite/definitions.test.js
- test/unit/adapters/sequelize.test.js
- test/unit/drivers/mysql.test.js
- test/unit/drivers/postgres.test.js
- test/unit/drivers/sqlite.test.js
> feat: TRUNCATE TABLE if possible

- index.js
- lib/adapters/sequelize.js
- lib/bone.js
- lib/drivers/abstract/spellbook.js
- lib/drivers/mysql/spellbook.js
- lib/hint.js
- lib/spell.js
- test/start.sh
- test/unit/adapters/sequelize.test.js
- test/unit/hint.test.js
- test/unit/realm.test.js
- test/unit/spell.test.js
* [optimizer-hints](https://dev.mysql.com/doc/refman/5.7/en/optimizer-hints.html)
* [index-hints](https://dev.mysql.com/doc/refman/5.7/en/index-hints.html)
* [mssql-hints](https://docs.microsoft.com/en-us/sql/t-sql/queries/hints-transact-sql?view=sql-server-ver15) not support
```js
// pass hint object
Post.create({ title: 'New Post', createdAt: date, updatedAt: date }, { hint: new Hint('SET_VAR(foreign_key_checks=OFF)') })
// INSERT /*+ SET_VAR(foreign_key_checks=OFF) */ INTO `articles` (`gmt_create`, `gmt_modified`, `title`) VALUES ('2017-12-12 00:00:00.000
// pass plain object
Post.create({ title: 'New Post', createdAt: date, updatedAt: date }, { hint: { value: 'SET_VAR(foreign_key_checks=OFF) }} })
// INSERT /*+ SET_VAR(foreign_key_checks=OFF) */ INTO `articles` (`gmt_create`, …
```
> feat: hint

- .github/workflows/nodejs.yml
- .github/workflows/npmpublish.yml
- History.md
- package.json
> release: v1.4.0-alpha.2

- CNAME
- History.md
- package.json
> release: 1.4.0-alpha.3

- docs/_layouts/zh.html
- docs/migrations.md
- docs/setup/egg.md
- docs/setup/express.md
- docs/zh/migrations.md
- docs/zh/setup/egg.md
- docs/zh/setup/expresss.md
- index.js
> docs: about egg-orm & migrations

- History.md
- docs/assets/css/style.scss
- package.json
> release: v1.4.1

- lib/bone.js
- lib/data_types.js
- lib/drivers/abstract/attribute.js
- test/dumpfile.sql
- test/integration/mysql.test.js
- test/integration/suite/basics.test.js
- test/models/user.js
- test/prepare.sh
> fix: support more data types (mediumtext, mediumint, char, date...)

- History.md
- index.js
- src/drivers/abstract/index.js
- src/drivers/mysql/spellbook.js
- src/spell.js
- test/unit/drivers/abstract/index.test.js
- test/unit/realm.test.js
... to let users intercept lower level api calls
> fix: export Logger and Spell

- src/drivers/abstract/index.js
- test/unit/drivers/abstract/index.test.js
...when interacting with database
> fix: convert datetime in seconds/milliseconds back to Date

- src/adapters/sequelize.js
- src/drivers/abstract/schema.js
- src/drivers/sqlite/schema.js
- test/unit/adapters/sequelize.test.js
Model.describe() runs a describe query on table
> fix: this.Model and proper Model.describe()

- index.js
- test/unit/realm.test.js
> fix: define assign Bone.models

- src/adapters/sequelize.js
- test/unit/adapters/sequelize.test.js
...to increase coverage
- https://coveralls.io/builds/41445891/source?filename=src%2Fadapters%2Fsequelize.js
> test: more tests cases about sequelize adapter

- test/start.sh
... which is not included in test:unit by default
> test: include test/unit/utils

- src/drivers/abstract/spellbook.js
- test/dumpfile.sql
- test/unit/drivers/abstract/spellbook.test.js
compound queries like arithmetic divide is used in existing code, fix this as a regression issue
> fix: where('width / height >= 16 / 9')

- .github/workflows/nodejs.yml
- .github/workflows/npmpublish.yml
- index.js
- src/collection.js
- src/data_types.js
- src/drivers/abstract/attribute.js
- src/drivers/mysql/data_types.js
- src/drivers/mysql/schema.js
- src/drivers/postgres/data_types.js
- src/drivers/postgres/schema.js
- src/drivers/sqlite/schema.js
- test/integration/suite/data_types.test.js
- test/unit/collection.test.js
- test/unit/data_types.test.js
- test/unit/drivers/mysql/attribute.test.js
- test/unit/drivers/postgres/attribute.test.js
- test/unit/drivers/sqlite/index.test.js
- test/unit/utils/index.test.js
> fix: JSONB in PostgreSQL & JSON as TEXT

- src/bone.js
- test/integration/suite/basics.test.js
```js
const user = await User.first;
user.toJSON();
user.createdAt  // should be an instance of Date
```
> fix: prevent from calling Date.prototype.toJSON

- src/drivers/abstract/spellbook.js
- test/integration/postgres.test.js
- test/integration/sqlite.test.js
- test/unit/spell.test.js
fix `upsert` set  value without `created_at`
> fix: upsert created_at default

- index.js
- test/unit/realm.test.js
> fix: raw query relpacements fix #149

- src/drivers/abstract/index.js
- src/drivers/mysql/index.js
- src/drivers/mysql/schema.js
- src/drivers/postgres/index.js
- src/drivers/sqlite/index.js
- test/unit/adapters/sequelize.test.js
- test/unit/drivers/abstract/index.test.js
- test/unit/drivers/mysql/index.test.js
- test/unit/drivers/postgres/index.test.js
- test/unit/drivers/sqlite/index.test.js
fixes #148, closes #60 with a mocked Pool and Connection for sqlite driver
> feat: close connections that exceeds opts.idleTimeout

- src/adapters/sequelize.js
- src/spell.js
- test/unit/adapters/sequelize.test.js
- test/unit/spell.test.js
> feat: silent option fix #164

- index.js
- src/adapters/sequelize.js
- src/bone.js
- src/drivers/abstract/schema.js
- src/drivers/mysql/schema.js
- src/drivers/sqlite/schema.js
- test/integration/suite/definitions.test.js
- test/unit/adapters/sequelize.test.js
- test/unit/drivers/sqlite/index.test.js
> breaking: drop the deprecated `Model.describe()`

- src/bone.js
- test/dumpfile.sql
- test/integration/suite/basics.test.js
- test/integration/suite/definitions.test.js
- test/models/post.js
- test/unit/spell.test.js
> fix: bulkCreate(...records) should recognize custom setters

- index.js
- test/unit/realm.test.js
> refactor: entry.isFile() can only be called as method

- src/data_types.js
- src/drivers/abstract/attribute.js
- src/drivers/abstract/index.js
- src/drivers/postgres/data_types.js
- src/drivers/sqlite/data_types.js
- test/integration/suite/data_types.test.js
- test/unit/collection.test.js
- test/unit/data_types.test.js
- test/unit/drivers/abstract/index.test.js
- test/unit/drivers/mysql/index.test.js
- test/unit/drivers/postgres/data_types.test.js
- test/unit/drivers/postgres/index.test.js
- test/unit/drivers/sqlite/data_types.test.js
- test/unit/drivers/sqlite/index.test.js
> feat: support STRING.BINARY(length), complete unit test

- .github/workflows/nodejs.yml
- docs/setup/index.md
- docs/setup/mysql.md
- docs/setup/postgres.md
- docs/setup/sqlite.md
- src/drivers/sqlite/connection.js
- src/drivers/sqlite/pool.js
- src/spell.js
- test/integration/sqlcipher.test.js
- test/unit/drivers/sqlite/pool.test.js
> fix: set options.busyTimeout to mitigate SQLITE_BUSY

- docs/_layouts/en.html
- docs/_layouts/zh.html
- docs/zh/contributing/guides.md
- types/index.d.ts
- types/leoric-tests.ts
> docs: how to contribute

- docs/zh/setup/egg.md
- src/bone.js
- test/unit/realm.test.js
> fix: Bone.load() should be idempotent, make sure associations is intact

- src/drivers/abstract/spellbook.js
- src/spell.js
- test/unit/spell.test.js
```js
Post.where({
$or: [
{ title: 'foo', authorId: 1 },
{ title: 'bar', authorId: 2 },
],
);
```
> fix: logical operator with multiple conditions such as

- src/drivers/mysql/index.js
> fix: opts.connectTimeout

- src/bone.js
- test/integration/suite/querying.test.js
> fix: reload instance with sharding key should not throw

- src/bone.js
- src/drivers/abstract/attribute.js
- src/drivers/postgres/attribute.js
- src/drivers/postgres/schema.js
- src/realm.js
- test/integration/suite/definitions.test.js
- test/unit/bone.test.js
- test/unit/drivers/postgres/index.test.js
- test/unit/realm.test.js
and should not be active if not actually defined in database
> fix: timestamps should be defined by default

- src/bone.js
- test/unit/adapters/sequelize.test.js
- test/unit/bone.test.js
> fix: instance.reload() should not rely on `static findOne()`

- test/types/collection.test.ts
- types/index.d.ts
```
error TS2614: Module '"leoric"' has no exported member 'Collection'. Did you mean to use 'import Collection from "leoric"' instead?
```
> docs: export { Collection }

- .github/workflows/nodejs.yml
- test/integration/postgres.test.js
- test/integration/suite/dates.test.js
> test: PostgreSQL v14 test case compatibility

- src/drivers/abstract/spellbook.js
- test/integration/suite/associations.test.js
- test/integration/suite/querying.test.js
> fix: turn off subquery optimization if query criteria contains other column

- src/bone.js
- test/integration/suite/basics.test.js
> fix: bulkCreate should adapting empty data input

- src/drivers/mysql/index.js
- src/drivers/postgres/index.js
- src/drivers/sqlite/index.js
- src/utils/index.js
detail see eggjs/egg-logger#74
before:
```log
[query] [1] DROP TABLE IF EXISTS `clients`
```
after:
```log
[query] [1.478] DROP TABLE IF EXISTS `clients`
```
> feat: make duration in precise milliseconds

- src/collection.js
- test/types/basics.test.ts
- types/index.d.ts
> fix: spell.increment() & spell.decrement()

- test/types/basics.test.ts
- types/index.d.ts
> fix: return type of spell modifier methods & test cases

- src/drivers/abstract/spellbook.js
- test/integration/suite/basics.test.js
> fix: update with empty conditions

- src/bone.js
- src/spell.js
- test/integration/suite/basics.test.js
- test/unit/spell.test.js
> fix: silent option's priority should be lower than valueSet

- src/bone.js
- src/data_types.js
- src/drivers/abstract/spellbook.js
- src/drivers/mysql/schema.js
- src/drivers/postgres/attribute.js
- src/drivers/postgres/schema.js
- src/drivers/sqlite/data_types.js
- src/drivers/sqlite/schema.js
- src/query_object.js
- src/raw.js
- src/realm.js
- src/spell.js
- test/integration/suite/basics.test.js
- test/integration/suite/data_types.test.js
- test/prepare.sh
- test/unit/adapters/sequelize.test.js
- test/unit/bone.test.js
- test/unit/data_types.test.js
- test/unit/drivers/mysql/index.test.js
- test/unit/drivers/postgres/index.test.js
- test/unit/drivers/sqlite/index.test.js
`new Model(values)` should have values rounded according to precision
> fix: information_schema.columns.datetime_precision

- src/collection.js
- test/integration/suite/querying.test.js
> fix: should still return number if value is '0.000'

- src/data_types.js
- test/unit/data_types.test.js
> fix: fix #257 DataType.uncast should skip Raw type at type checking

- docs/querying.md
- docs/zh/querying.md
> docs: async function in transaction

- src/drivers/abstract/spellbook.js
- src/drivers/mysql/spellbook.js
> refactor: keep the UPDATE ... ORDER BY ... LIMIT to mysql driver

- src/bone.js
- test/integration/suite/basics.test.js
> fix: fix restore Error `Undefined attribute "deletedAt"`

- src/bone.js
- test/unit/bone.test.js
> fix: default updatedAt to new date if model has no createdAt

- src/adapters/sequelize.js
- test/unit/adapters/sequelize.test.js
> feat: fix #270 sequelize mode bulkBuild

- src/adapters/sequelize.js
- src/bone.js
- test/integration/suite/basics.test.js
- test/unit/adapters/sequelize.test.js
> fix: fix #274 update with fields option

- index.js
- src/data_types.js
- src/drivers/abstract/attribute.js
- src/drivers/postgres/data_types.js
- src/realm.js
- test/unit/bone.test.js
- test/unit/data_types.test.js
- test/unit/drivers/postgres/data_types.test.js
- https://www.yuque.com/leoric/blog/integer
- https://www.postgresql.org/docs/8.1/datatype.html
- https://www.sqlite.org/datatype3.html
- https://dev.mysql.com/doc/refman/8.0/en/integer-types.html
closes #279
> feat: integer types (mostly mysql specific)

- index.js
- src/realm.js
- test/unit/realm.test.js
> fix: realm.DataTypes should be invokable

- src/bone.js
- src/drivers/abstract/attribute.js
- test/dumpfile.sql
- test/unit/adapters/sequelize.test.js
- test/unit/drivers/mysql/attribute.test.js
... to ignore defaults like `CURRENT_TIMESTAMP`
> fix: normalize attribute defaultValue

- docs/api/Bone.html
- src/bone.js
- src/drivers/mysql/index.js
- src/drivers/postgres/index.js
- src/drivers/sqlite/index.js
- src/setup_hooks.js
- test/integration/suite/associations.test.js
- test/integration/suite/basics.test.js
- test/integration/suite/querying.test.js
- test/unit/adapters/sequelize.test.js
- test/unit/drivers/mysql/index.test.js
- test/unit/drivers/postgres/index.test.js
- test/unit/drivers/sqlite/index.test.js
- test/unit/hooks.test.js
- types/index.d.ts
and remove unset attribute warning log
> feat: logger support trans result in callback arguments

- .gitignore
- index.js
- package.json
- src/bone.js
- src/constants.js
- src/decorators.ts
- src/drivers/abstract/attribute.js
- test/integration/suite/data_types.test.js
- test/start.sh
- test/types/basics.test.ts
- test/types/decorators.test.ts
- test/types/querying.test.ts
- test/unit/bone.test.js
- tsconfig.json
- types/index.d.ts
- https://www.yuque.com/leoric/blog/sgifi3 (zh-cn)
> feat: model declaration with decorators

- src/bone.js
- src/collection.js
- src/data_types.js
- src/drivers/abstract/attribute.js
- src/drivers/abstract/spellbook.js
- src/drivers/mysql/spellbook.js
- src/drivers/sqlite/spellbook.js
- src/expr_formatter.js
- src/spell.js
- test/integration/suite/basics.test.js
- test/models/user.js
- test/unit/bone.test.js
- test/unit/data_types.test.js
- test/unit/hooks.test.js
- types/data_types.d.ts
> feat: add VIRTUAL data type

- src/bone.js
- test/integration/suite/basics.test.js
> fix: mysql2 Invalid Date compatible

- src/adapters/sequelize.js
- test/unit/adapters/sequelize.test.js
> fix:  bulk update query conditions duplicated in sequelize mode

- src/bone.js
- src/data_types.js
- src/drivers/abstract/attribute.js
- src/drivers/abstract/schema.js
- src/drivers/mysql/attribute.js
- src/drivers/mysql/schema.js
- src/drivers/postgres/schema.js
- src/drivers/sqlite/schema.js
- test/integration/suite/basics.test.js
- test/integration/suite/definitions.test.js
- test/unit/bone.test.js
- test/unit/connect.test.js
- test/unit/data_types.test.js
- test/unit/drivers/mysql/attribute.test.js
- types/data_types.d.ts
also (partially) added column comment support to close #294
> fix: drop column if not defined in attributes when alter table

- src/adapters/sequelize.js
- test/unit/adapters/sequelize.test.js
> fix: order by raw with mix-type array in sequelize mode

- docs/_layouts/en.html
- docs/_layouts/zh.html
- docs/assets/css/style.scss
- docs/index.md
- docs/zh/basics.md
- docs/zh/index.md
> docs: elaborate on querying

- src/bone.js
- test/integration/suite/querying.test.js
- test/unit/adapters/sequelize.test.js
- test/unit/realm.test.js
> feat: transaction should return result

- index.js
- package.json
- src/bone.js
- src/hint.js
- test/types/custom_driver.ts
- types/hint.d.ts
- types/index.d.ts
> feat: export more ts type definitions and  use deep-equal module

- index.js
- src/bone.js
- src/constants.js
- src/drivers/abstract/index.js
- src/realm.js
- test/integration/custom.test.js
- test/unit/timestamp.test.js
- types/index.d.ts
> feat: support disconnect and fix timestamps init

- src/drivers/mysql/index.js
- src/drivers/postgres/index.js
- src/drivers/sqlite/index.js
- test/unit/drivers/mysql/index.test.js
- test/unit/drivers/postgres/index.test.js
- test/unit/drivers/sqlite/index.test.js
- types/index.d.ts
> feat: support export sql query template in logger

- .github/workflows/nodejs.yml
- .github/workflows/npmpublish.yml
- src/data_types.js
- test/integration/postgres.test.js
- test/integration/suite/data_types.test.js
- test/prepare.sh
- test/unit/drivers/postgres/index.test.js
- test/unit/realm.test.js
> build: switch to latest postgres

- test/prepare.sh
... to the one that's supported
> test: switch the auth protocol of test mysql database 

- test/types/querying.test.ts
- types/index.d.ts
> docs: fix declarations of findOne(primaryKey) & findOne({ $or })

- src/drivers/mysql/index.js
- src/realm.js
- test/unit/realm.test.js
> fix: glue code for opts.dialectModulePath

- index.d.ts
- package.json
> fix: declare more exported functions such as isBone and heresql

- src/expr.js
- test/unit/expr.test.js
> fix: throw error if token is not expected when parse expr

- index.js
- src/adapters/sequelize.js
- src/realm.js
- test/unit/adapters/sequelize.test.js
metro bundler didn't support `exports.name = this.otherFuc()`;
> fix: metro exports error

- src/types/common.d.ts
- test/models/tag.js
- test/types/decorators.test.ts
> fix: AssociateOptions in HasMany, BelongdsTo decorators

- src/adapters/sequelize.d.ts
- src/decorators.ts
- src/types/abstract_bone.d.ts
- src/types/common.d.ts
- test/types/decorators.test.ts
> fix: invokable dataType in decorators should work and dts fix

- src/adapters/sequelize.d.ts
- src/bone.d.ts
- src/bone.js
- src/data_types.ts
- src/drivers/index.d.ts
- src/drivers/sqlite/data_types.js
- src/spell.d.ts
- src/spell.js
- src/types/abstract_bone.d.ts
- src/types/common.d.ts
- test/integration/suite/data_types.test.js
- test/types/basics.test.ts
- test/types/querying.test.ts
- test/types/sequelize.test.ts
use Record<string, any> instead
> fix: Literal type should not contain `object` & ResultSet should be derived from instance values

- index.d.ts
- src/bone.js
- src/drivers/abstract/attribute.js
- src/spell.js
- src/types/abstract_bone.d.ts
- src/types/common.d.ts
- test/dumpfile.sql
- test/types/realm.test.ts
- test/unit/spell.test.js
> fix: deletedAt should always be checked when associating models

- index.js
- src/realm.js
- test/unit/realm.test.js
> fix: new Realm({ sequelize: true }).Bone == Realm.SequelizeBone

- src/bone.js
- src/data_types.ts
- src/drivers/abstract/attribute.js
- test/unit/bone.test.js
- test/unit/data_types.test.js
- test/unit/drivers/abstract/attribute.test.js
> fix: edge cases in attribute.equals()

- src/types/abstract_bone.d.ts
- test/types/basics.test.ts
> fix: bone.attribute(name, value?) type infer with this[name]

- src/data_types.ts
- src/types/abstract_bone.d.ts
- test/types/basics.test.ts
- test/types/custom_driver.test.ts
- test/types/decorators.test.ts
- test/types/querying.test.ts
- test/types/sequelize.test.ts
- tsconfig.json
> fix: enable strictNullChecks

- index.d.ts
- src/types/common.d.ts
- test/integration/sqlcipher.test.js
- test/types/basics.test.ts
- test/types/realm.test.ts
> fix: declaration types of realm.query() and static update values

- src/drivers/abstract/spellbook.js
- src/drivers/postgres/index.js
- test/integration/suite/querying.test.js
> fix: join query with select columns should include order columns

- docs/_config.yml
- docs/_layouts/en.html
- docs/_layouts/zh.html
- docs/assets/css/style.scss
- docs/assets/javascript/app.mjs
- src/drivers/postgres/index.js
> docs: support switchable dark theme, at web app level

- src/decorators.ts
- test/types/decorators.test.ts
- https://github.com/eggjs/egg-orm/pull/29
> fix: @Column() should not tamper parent attributes directly

- src/bone.js
- src/spell.js
- test/integration/suite/basics.test.js
> fix: bone.update({ deletedAt: null }) and likewise methods should work

- src/adapters/sequelize.d.ts
- src/data_types.ts
- src/decorators.ts
- src/types/abstract_bone.d.ts
- src/types/common.d.ts
- test/types/basics.test.ts
- test/types/data_types.test.ts
- test/types/sequelize.test.ts
> fix: `tinytext` type error

- src/bone.js
- src/drivers/abstract/index.js
- test/unit/realm.test.js
> feat: support manual rollback & commit for transaction, fix #371

- .gitignore
- src/realm.js
- src/spell.js
- test/integration/suite/sharding.test.ts
- test/models/photo.ts
- test/start.sh
> fix: retain where conditions when sharding key is necessary

- Readme.md
- src/spell.js
- test/unit/spell.test.js
to retain the expected result order
> fix: order clause need be repeated on the main query

- docs/index.md
- docs/setup/egg.md
- docs/setup/midway.md
- docs/zh/index.md
- docs/zh/setup/egg.md
- docs/zh/setup/midway.md
> docs: introduce @midwayjs/leoric

- src/adapters/sequelize.d.ts
- src/spell.d.ts
- test/types/sequelize.test.ts
> fix: sequelize addHook type definition

- package.json
<https://nodejs.org/api/packages.html#main-entry-point-export>
> chore: export main entry point only

- docs/associations.md
- docs/basics.md
- docs/types.md
- docs/zh/associations.md
- docs/zh/basics.md
- docs/zh/types.md
> docs: more examples about typescript support

- src/collection.js
- test/unit/collection.test.js
> fix: Collection[null].toJSON()
