cyjake/leoric

.travis.yml, lib/bone.js, package.json, test/suite/basics.js, test/suite/querying.js
even with `UPDATE id = LAST_INSERT_ID(id)` hack https://stackoverflow.com/questions/778534/mysql-on-duplicate-key-last-insert-id
cc @chenhui5416
=> fix: LAST_INSERT_ID() breaks on some MySQL compliant databases

lib/adapters/sequelize.js, lib/bone.js, test/unit/adapters/test.sequelize.js
... where as findOne() still returns an arbitrary row
=> fix: findOne(null|undefined) shall return null

lib/bone.js, lib/validator.js, test/integration/suite/basics.test.js, test/unit/adapters/sequelize.test.js, test/unit/validator.test.js
fix: instance[key] should not change after updating failed
eg.
```js
const user = new User({
email: 'a@e.com',
nickname: 'sss',
fingerprint: 'finger111'
});
try {
// assume it will be failed
await user.update({ fingerprint: 'aaa' });
} catch (err) {}
user.fingerprint // should be 'finger111', not 'aaa'
```
=> fix: instance[key] should not change after updating failed

History.md, lib/bone.js, lib/spell.js, package.json
* feat: support multiple order rules in one single string or one-dimensional array (#92)
* feat: `realm.raw('SELECT ...')` and `Model.raw('SELECT ...')`
* feat: `Model.truncate()` now uses TRUNCATE if possible
* feat: `Model.find().optimizerHints('SET_VAR(foreign_key_checks=OFF)')`
* fix: make sure connection is passed around in all queries carried out within transaction
* docs: migrations, validations, hooks, and sequelize adapter
=> release: v1.4.0-alpha.1

docs/contributing/guides.md
Previous instructions were outdated as Homebrew uses a different directory on Apple Silicon. Easier to link to current instructions on the Jekyll website, plus give a link to a complete guide at mac.install.guide that explains the pitfalls of using Homebrew to install Ruby, and point to Moncef Belyamani's Ruby setup scripts. Hope this helps!
=> revise instructions for installing Jekyll

lib/drivers/abstract/schema.js, package.json, test/integration/suite/basics.test.js
```js
await Post.bulkCreate([
{ missingKey: 'foo' },
]);
```
=> fix: Bone.bulkCreate() should not throw when called with non attribute

index.js, lib/bone.js, test/integration/suite/basics.test.js, test/integration/suite/migrations.test.js, test/models/tag.js, test/unit/connect.test.js, test/unit/hint.test.js, test/unit/realm.test.js, test/unit/spell.test.js
- gather around glue code for legacy timestamp
=> refactor: do not subclass by default

src/bone.js, test/integration/suite/basics.test.js, test/integration/suite/querying.test.js, test/models/post.js, test/unit/utils/index.test.js
```js
class Foo {
get a() {}
}
```
`foo.a` is not enumerable by default, Leoric should leave it that way. If users want them to be enumerable, they need to redefine them explicitly
=> fix: leave the getter properties defined in `class` syntax as is

src/bone.js, test/integration/suite/basics.test.js, test/models/post.js
even if overridden by getters in class syntax
=> fix: names defined in Bone.attributes should always be enumerable

docs/hooks.md, docs/validations.md, docs/zh/hooks.md, docs/zh/validations.md, index.js, src/bone.js, src/collection.js, src/drivers/abstract/spellbook.js, src/drivers/postgres/index.js, src/drivers/sqlite/index.js, src/drivers/sqlite/spellbook.js, src/setup_hooks.js, src/spell.js, test/integration/suite/definitions.test.js, test/models/attachment.js, test/models/comment.js, test/models/post.js, test/models/tag.js, test/models/tagMap.js, test/unit/bone.test.js, test/unit/connect.test.js, test/unit/realm.test.js
```js
class User extends Bone {
static attributes = {}
static beforeCreate(obj) {
}
static initialize() {
this.hasMany('posts');
}
}
```
- deprecated `Bone.describe()`, migrating to `Bone.initialize()`.
- renamed `Bone.aliasName` to `Bone.tableAlias`, which is an internal property
=> feat: support class static attributes

src/collection.js, test/unit/collection.test.js
- vanilla mysql: `[ { '': { count: 1 } } ]`
- tddl: `[ { [table]: { count: 1 } } ]`
=> fix: collection convert should handle tddl results as well

src/adapters/sequelize.js, src/bone.js, test/unit/adapters/sequelize.test.js, test/unit/bone.test.js
even if there is getter method with same name. Also added `Model.Instance` in sequelize adapter
=> fix: renamed attribute should remain enumerable

src/spell.js, test/unit/adapters/sequelize.test.js
```js
// sequelize
await realm.transaction(async function(transaction) {
await User.create(values, { transaction })
});
// leoric
await realm.transaction(async function({ connection }) {
await User.create(values, { connection })
});
```
Connection will be passed to Spell in `opts.transaction`
=> fix: transaction option passing in sequelize adapter

src/drivers/abstract/schema.js
```
[query] [85564] DESCRIBE TABLE `activities`
2021-07-15 16:28:22,908 ERROR 754 nodejs.unhandledRejectionError: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'TABLE `activities`' at line 1
at Packet.asError (./node_modules/_mysql2@1.7.0@mysql2/lib/packets/packet.js:708:17)
at Query.execute (./node_modules/_mysql2@1.7.0@mysql2/lib/commands/command.js:28:26)
at PoolConnection.handlePacket (./node_modules/_mysql2@1.7.0@mysql2/lib/connection.js:408:32)
at PacketParser.onPacket (./node_modules/_mysql2@1.7.0@mysql2/lib/connection.js:70:12)
at PacketParser.executeStart (./node_modules/_mysql2@1.7.0@mysql2/lib/packet_parser.js:75:16)
at Socket.<anonymous> …
```
=> fix: describe table with more compatible syntax

index.js, package.json, src/drivers/abstract/spellbook.js, src/expr.js, src/utils/string.js, test/unit/drivers/abstract/spellbook.test.js, test/unit/spell.test.js
Leoric tries to optimize join queries that have offset or limit by putting them into a subquery. If the subquery itself contains another Spell as subquery, such as:
```js
Post
.where({
isPrivate: true,
authorId: User.where({ stauts: 1 }),
})
.with('author')
.limit(10);
```
will be formatted into following SQL:
```sql
SELECT posts.*, users.* 
FROM (SELECT * FROM users WHERE is_private = 1 AND author_id IN (...) LIMIT 10);
```
This optimization should not tamp the subquery `User.where({ status: 1 })` passed to `Post.where({}`.
=> fix: select join with subqueries should not tamper the subquery itself

.eslintrc, docs/contributing/guides.md, docs/zh/contributing/guides.md, index.js, package.json, src/spell.js, test/integration/postgres.test.js, test/integration/sqlite.test.js, test/integration/suite/basics.test.js, test/start.sh, test/unit/adapters/sequelize.test.js, test/unit/bone.test.js, test/unit/connect.test.js, test/unit/drivers/abstract/spellbook.test.js, test/unit/hint.test.js, test/unit/hooks.test.js, test/unit/realm.test.js, test/unit/spell.test.js, test/unit/utils/string.test.js, test/unit/validator.test.js
...at least for test:unit, especially in following scenario:
```js
class Spine extends Bone {}
class Book extends Spine {}
await connect({ Bone: Spine });
```
which connects `Spine.driver` without polluting `Bone.driver`. Handy for test cases.
=> refactor: connect({ Bone }) still necessary

index.js, test/unit/realm.test.js
also changed test cases a bit, `assert.rejects(async function() {}, 'Error: xxx')` won't work in most cases because of argument ambiguousness. 
references (Custom error validation):
- https://nodejs.org/api/assert.html#assert_assert_rejects_asyncfn_error_message
- https://nodejs.org/api/assert.html#assert_assert_throws_fn_error_message
=> refactor: break implementation into normalize/replacement/query

src/validator.js, test/unit/validator.test.js
```js
bone.define('User', {
status: {
type: STRING,
validate: {
isIn: {
args: [ [ '1', '2' ] ], // not [ '1', '2' ]
msg: 'Error status',
},
}
}
})
```
=> fix: validator call array arguments

History.md, src/bone.js, src/drivers/abstract/attribute.js, src/drivers/sqlite/connection.js, src/drivers/sqlite/index.js, src/drivers/sqlite/pool.js, src/validator.js, test/unit/drivers/sqlite/pool.test.js
`attribute.defaultValue` currently have two mixed responsibility:
- the default value set in table schema
- the default value to be set when saving records via model methods
=> fix: attribute.equals() check should ignore defaultValue

package.json, src/drivers/sqlite/connection.js, src/drivers/sqlite/pool.js, test/integration/sqlcipher.test.js, test/integration/sqlite.test.js, test/integration/suite/migrations.test.js, test/unit/drivers/sqlite/index.test.js
added integration test with @journeyapps/sqlcipher client
before:
```js
1) => SQLite driver.query()
should support async stack trace:
Error: SQLITE_ERROR: no such table: missing
```
after:
```js
1) => SQLite driver.query()
should support async stack trace:
Error: SQLITE_ERROR: no such table: missing
--> in Database#all('SELECT * FROM missing', undefined, [Function: Leoric_all])
at /Users/nil/Projects/cyjake/leoric/src/drivers/sqlite/connection.js:48:21
at new Promise (<anonymous>)
at Connection.all (src/drivers/sqlite/connection.js:47:12)
at Connection.query (src/drivers/sqlite/connection.js:39:33)
at SqliteDriver.query (src/drivers/sqlite/index.js:46:33)
at async Context.<anonymous> (test/unit/drivers/sqlite/index.test.js:181:7)
```
=> fix: turn on long stack trace of sqlite driver

src/bone.js, test/integration/suite/basics.test.js, test/unit/adapters/sequelize.test.js
=> fix: selected instance isNewRecord should be false

src/drivers/abstract/spellbook.js, src/expr_formatter.js, src/query_object.js, src/spell.js, test/unit/query_object.test.js, test/unit/spell.test.js
- object condition parsing => src/query_object.js
- expression formatting => src/expr_formatter.js
currently the `spell` object is still passed along the `formatXxx()` functions in expr_formatter.js. There might be two ways to refactor this:
- Turn `formatXxx()` into `ExprFormatter()` instances with `this.spell`;
- Turn expr objects into `Expr`, `OpExpr`, etc. with `this.spell`;
both requires lots of work but without little perf improvements, hence postponded further.
=> refactor: object condition parsing and expression formatting

src/bone.js, test/unit/bone.test.js
do not add default timestamps if timestamps in snake case exists already
=> fix: accept timestamps in snake case

src/drivers/abstract/logger.js, src/drivers/mysql/index.js, src/drivers/postgres/index.js, src/drivers/sqlite/index.js, test/unit/drivers/abstract/index.test.js, test/unit/realm.test.js
#39 logger.logQuery should be guarded in case of error
=> fix: logger.logQuery should be guarded in case of error

src/bone.js, src/realm.js, test/integration/suite/definitions.test.js, test/unit/realm.test.js
=> feat: model.sync add force/alter option

test/types/basics.test.ts, test/types/collection.test.ts, test/types/querying.test.ts, types/index.d.ts
=> fix: select((name: string) => boolean)

src/drivers/mysql/index.js, src/drivers/postgres/index.js, src/drivers/sqlite/index.js, src/utils/index.js
detail see eggjs/egg-logger#74
before:
```log
[query] [1] DROP TABLE IF EXISTS `clients`
```
after:
```log
[query] [1.478] DROP TABLE IF EXISTS `clients`
```
=> feat: make duration in precise milliseconds

src/drivers/mysql/index.js, src/drivers/postgres/index.js, src/drivers/sqlite/index.js, test/unit/drivers/mysql/index.test.js, test/unit/drivers/postgres/index.test.js, test/unit/drivers/sqlite/index.test.js
to correct a bad design in v1.x, change from `logQueryError(sql, err, ...)` to `logQueryError(err, sql, ...)`
=> breaking: logQueryError(err, sql, duration, options)

src/data_types.js, test/unit/data_types.test.js
=> fix: fix #242 date string format

src/drivers/abstract/spellbook.js, test/integration/suite/associations.test.js
```js
const result = await Post.include('comments').order('comments.id', 'desc').order('posts.id', 'desc').limit(1);
```
This query might retrives wrong result because the post with latest comments isn't necessarily the latest one, such as:
| post_id | comment_id |
|---------|------------|
| 1       | 3          |
| 2       | 2          |
| 3       | 1          |
Previous implementation will yield SQL like:
```sql
SELECT posts.*, comments.*
FROM (SELECT * FROM posts ORDER BY id DESC)
AS posts
LEFT JOIN comments ON posts.id = comments.post_id
ORDER BY comments.id desc
```
which retrives `Post<#id 3>`, but `Post<#id 1>` is the one with the latest comment.
=> fix: should not hoist subquery if query is ordered by external columns

History.md, package.json, src/bone.js, src/data_types.js, src/drivers/abstract/spellbook.js, src/drivers/mysql/schema.js, src/drivers/postgres/attribute.js, src/drivers/postgres/schema.js, src/drivers/sqlite/data_types.js, src/drivers/sqlite/schema.js, src/query_object.js, src/raw.js, src/realm.js, src/spell.js, test/integration/suite/associations.test.js, test/integration/suite/basics.test.js, test/integration/suite/data_types.test.js, test/prepare.sh, test/unit/adapters/sequelize.test.js, test/unit/bone.test.js, test/unit/data_types.test.js, test/unit/drivers/mysql/index.test.js, test/unit/drivers/postgres/index.test.js, test/unit/drivers/sqlite/index.test.js, test/unit/spell.test.js
=> Merge 1.x changes

src/collection.js, src/contants.js, src/spell.js, test/integration/suite/index.test.js, test/integration/suite/querying.test.js, test/integration/suite/string.test.js
=> fix: format numeric result

src/drivers/abstract/spellbook.js, test/integration/suite/associations.test.js
```js
TypeError: Cannot read property 'length' of undefined
at checkQualifier (src/drivers/abstract/spellbook.js:224:39)
at walkExpr (src/expr.js:415:3)
at Object.formatSelectWithJoin (src/drivers/abstract/spellbook.js:229:37)
at Object.formatSelect (src/drivers/abstract/spellbook.js:292:12)
at Object.format (src/drivers/abstract/spellbook.js:572:21)
at MysqlDriver.format (src/drivers/mysql/index.js:109:22)
at Spell.ignite (src/spell.js:428:42)
at Spell.then (src/spell.js:447:17)
```
=> fix: order by alias should not throw

src/adapters/sequelize.js, src/drivers/abstract/spellbook.js, src/drivers/mysql/spellbook.js, test/integration/suite/basics.test.js, test/unit/adapters/sequelize.test.js, test/unit/spell.test.js
=> fix: fix #260 UPDATE with LIMIT and ORDER should be formatted(mysql only)

src/data_types.js, src/drivers/abstract/attribute.js, src/drivers/postgres/data_types.js, src/drivers/sqlite/data_types.js, src/expr_formatter.js, test/integration/suite/data_types.test.js, test/unit/data_types.test.js
DB/DataType(validate or not in SQL operations) | INTEGER | DATE
-- | -- | --
MySQL | 🔲query ✅insert | ✅query ✅insert
SQLlite | 🔲query 🔲insert | 🔲query 🔲insert
PostgresSQL | ✅query ✅insert | ✅query ✅insert
=> fix: type checking adaption

src/bone.js, src/drivers/postgres/schema.js, src/drivers/sqlite/schema.js, src/realm.js, test/dumpfile.sql, test/integration/postgres.test.js, test/integration/sqlite.test.js, test/integration/suite/basics.test.js, test/unit/adapters/sequelize.test.js, test/unit/hint.test.js, test/unit/spell.test.js
when loading attributes from information_schema, the `attribute.defaultValue` should be set as well to be compliant with the validation change introduced by https://github.com/cyjake/leoric/pull/262/files
=> fix: attribute.defaultValue should be set when init attributes

src/adapters/sequelize.js, src/bone.js, src/drivers/mysql/spellbook.js, test/integration/suite/basics.test.js, test/unit/adapters/sequelize.test.js
```js
Post.remove({ status: 1}, true).limit(n).order('id');
Post.remove({ status: 1}, false).limit(n).order('id');
// sequelize mode
Post.destroy({ where: { status: 1 }, limit: n, order: 'id' });
```
=> fix:  mysql delete/remove/destroy with limit and orders

src/drivers/abstract/spellbook.js, src/drivers/mysql/spellbook.js, test/integration/postgres.test.js, test/integration/sqlite.test.js, test/integration/suite/basics.test.js, test/unit/spell.test.js
```js
Post.upser({ title: 'yes' });
// INSERT INTO `posts` (`title`,  `created_at`, `updated_at`) VALUES ('yes', `currentTime`, `currentTime`) ON DUPLICATE KEY UPDATE `title` = VALUES(`title`), `updated_at` = VALUES(`updated_at`)
// set created_at in fields but not `ON DUPLICATE KEY UPDATE` options
Post.upsert({ title: 'yes', createdAt: 'currentTime' });
// INSERT INTO `posts` (`title`,  `created_at`, `updated_at`) VALUES ('yes', `currentTime`, `currentTime`) ON DUPLICATE KEY UPDATE `title` = VALUES(`title`), `created_at` = VALUES(`created_at`), `updated_at` = VALUES(`updated_at`)
```
=> fix:  upsert should set createdAt  by default while createdAt  not set 

src/bone.js, src/drivers/abstract/attribute.js, test/integration/suite/basics.test.js, test/integration/suite/data_types.test.js, test/unit/adapters/sequelize.test.js
```js
// title: Untitled, authorId: undefined
const post = new Post({ title: 'Untitled' });
assert.deepEqual(post.previousChanges('title'), {});
assert.deepEqual(post.previousChanges('authorId'), {});
post.title = 'MHW';
// authorId was undefined
post.authorId = 100;
await post.save();
// post is not a new record now
assert.deepEqual(post.previousChanges('authorId'), { authorId: [ null, 100 ] });
```
=> fix: previousChanges should check instance is new record or not while specific attributes' values were undefined

test/start.sh, test/types/realm.test.ts, tsconfig.json, types/index.d.ts
- Make the last two parameters optional of `Realm.prototype.define()`.
- Add `sync` method signature.
=> feat: add types for realm

test/types/realm.test.ts, types/index.d.ts
- Add missing `password` for `ConnectOptions`.
- Fix the return type of `Realm.prototype.define()`.
=> fix: add missing `password` field for `ConnectOptions`

src/realm.js
```sql
MySQL [CENTRAL_APP]> SELECT table_name FROM information_schema.columns WHERE table_schema = 'CENTRAL_APP' AND table_name in ('central_creations_logic_0000') LIMIT 1;
+-------------------------+
| table_name              |
+-------------------------+
| central_creations_logic |
+-------------------------+
1 row in set (0.03 sec)
```
=> fix: tddl gives misleading information_schema.columns.table_name

src/bone.js, src/setup_hooks.js, test/unit/hooks.test.js
=> fix: instance beforeUpdate hooks should not modify any Raw if there are no Raw  assignment  in them

src/bone.js, test/integration/suite/basics.test.js, test/unit/adapters/sequelize.test.js
=> fix: create instance dirty check rule fix

src/adapters/sequelize.js, test/unit/adapters/sequelize.test.js
=> fix: order by raw in sequelize mode

src/adapters/sequelize.js, test/unit/adapters/sequelize.test.js
=> fix:  bulk destroy query conditions duplicated in sequelize mode

src/realm.js, test/unit/realm.test.js
```js
const { rows } = await realm.query('SELECT * FROM articles where title = :title AND author_id = :authorId LIMIT :limit', {
replacements: {
title: post1.title,
authorId: 2,
limit: 1,
},
});
// actual: SELECT * FROM articles where title ='title1' AND author_id =2 LIMIT1 # may cause SQL syntax error
// expect: SELECT * FROM articles where title = 'title1' AND author_id = 2 LIMIT 1
```
=> fix: raw query should format replacements with extra blank

src/data_types.js, test/unit/data_types.test.js
```js
// return  Invalid Date  by jsCore
new Date("2021-10-15 15:50:02");
```
=> fix: fix uncast date string without milliseconds error by jsCore in Android/iOS

index.js, src/bone.js, src/constants.js, src/realm.js, src/utils/index.js, test/unit/utils/index.test.js
https://github.com/eggjs/egg-orm/blob/7086680f533b9efa70db55e06345adbb5ac321f5/lib/loader.js#L46
```
if (!(OriginModelClass && OriginModelClass.prototype && OriginModelClass.prototype instanceof Model)) {
return OriginModelClass;
}
// => 
if (!(Realm.isLeoricBone(OriginModelClass)) {
return OriginModelClass;
}
```
model class could be multiple inheritance, `OriginModelClass.prototype instanceof Model` cannot be a proper way to validate a model is a leoric bone
=> feat: add leoric_bone meta data to Bone

.eslintrc, package.json, src/adapters/sequelize.js, src/bone.js, src/drivers/abstract/index.js, src/drivers/abstract/spellbook.js, src/realm.js, test/integration/postgres.test.js, test/integration/sqlite.test.js, test/integration/suite/basics.test.js, test/unit/adapters/sequelize.test.js, test/unit/realm.test.js
```js
User.upsert({ email: 'dk@souls.com', nickname: 'Yhorm' }).toSqlString();
// email is unique, when values not contains primaryKey, it should be ON CONFLICT ("email")
// SQL: INSERT INTO "users" ("email", "nickname", "status", "level", "gmt_create") VALUES ('dk@souls.com', 'Yhorm', 1, 1, '2017-12-12 00:00:00.000') ON CONFLICT ("email") DO UPDATE SET "email"=EXCLUDED."email", "nickname"=EXCLUDED."nickname", "status"=EXCLUDED."status", "level"=EXCLUDED."level"
User.upsert({ email: 'dk@souls.com', nickname: 'Yhorm', id: 1 }).toSqlString();
//  when values contains primaryKey, it should be ON CONFLICT ("id")
// INSERT INTO "users" ("id", "email", "nickname", "status", "level", "gmt_create") VALUES (1, 'dk@souls.com', 'Yhorm', 1, 1, '2017-12-12 00:00:00.000') ON CONFLICT ("id") DO UPDATE …
```
=> fix: primaryKey in upsert values should be validate in sqlite and postgres

src/bone.js, src/data_types.ts, src/drivers/mysql/data_types.js, src/drivers/postgres/data_types.js, src/drivers/postgres/index.js, src/drivers/sqlite/data_types.js
=> fix: projects might have strictPropertyInitialization set to true

src/data_types.ts, src/decorators.ts, src/drivers/abstract/attribute.js, src/drivers/postgres/data_types.js, src/drivers/sqlite/data_types.js, test/types/decorators.test.ts, test/unit/data_types.test.js, test/unit/drivers/mysql/attribute.test.js, test/unit/drivers/postgres/attribute.test.js, test/unit/drivers/sqlite/attribute.test.js, test/unit/hooks.test.js
* INTEGER like data type and STRING extra options didn't work in polymorphism
```js
// `idd` INTEGER(2) UNSIGNED
new Attribute('idd', { type: new INTEGER(2).UNSIGNED }).toSqlString();
//`isbn` VARCHAR(60)
new Attribute('isbn', { type: new STRING(60) }).toSqlString();
```
* fix decorators ColumnOptions.type to support invokable
```ts
@Column({
type: STRING
})
body: string;
@Column({
type: STRING(64)
})
description: string;
@Column({
type: INTEGER(2).UNSIGNED,
})
status: number;
```
=> fix: INTEGER like data type and STRING extra options didn't work in polymorphism, fix decorators ColumnOptions.type to support invokable

src/realm.js
=> fix: should skip loading models that is loaded before

src/bone.js, src/types/common.d.ts, test/types/decorators.test.ts
also fixed an issue about bone.clone(), which didn't overwrite the original unset attribute set correctly
=> fix: AssociationOptions.select? should be supported

index.d.ts, src/bone.js, src/decorators.ts, src/realm.js, src/types/abstract_bone.d.ts, src/types/common.d.ts, test/integration/suite/querying.test.js, test/models/book.js, test/types/basics.test.ts, test/types/decorators.test.ts, test/types/realm.test.ts
also loosened up the default Bone.primaryKey a bit to allow subclass to override with `static primaryKey = ` etc.
=> fix: return type of realm.query, realm.transaction, and Bone.transation

src/adapters/sequelize.d.ts, src/types/abstract_bone.d.ts, src/types/common.d.ts, test/types/basics.test.ts, test/types/sequelize.test.ts
* attributeWas 
* QueryOptions.transaction support null
* sequelize instance.update
=> fix: ts type definitions

src/types/abstract_bone.d.ts, test/types/basics.test.ts
```ts
class Foo {
@Column(TEXT)
get settings(): Record<string, any> {
// this.attribute('settings') should return the original union type here
const text = this.attribute('settings') as string;
if (!text) return null;
try {
return JSON.parse(text);
} catch {
return null;
}
}
}
```
=> fix: this.attribute(name) should fallback to Literal

.gitignore, index.js, src/adapters/sequelize.d.ts, src/adapters/sequelize.js, src/bone.d.ts, src/bone.js, src/data_types.ts, src/drivers/abstract/spellbook.js, src/drivers/postgres/data_types.js, src/expr.js, src/query_object.js, src/raw.js, src/raw.ts, src/realm.js, src/spell.d.ts, src/spell.js, src/types/abstract_bone.d.ts, src/types/common.d.ts, test/integration/custom.test.js, test/types/basics.test.ts, test/types/custom_driver.test.ts, test/types/querying.test.ts, test/types/sequelize.test.ts, test/types/spell.test.ts, test/unit/data_types.test.js
* `this.attribute(columnName)`, `this.attribute(columnName, v)`
* `attributeWas` `previousChanged`
* `orderOptions`
* `minimum(columnName)` and others
=> fix: type definitions for columns constraint

package.json, src/data_types.ts, src/drivers/mysql/spellbook.js, src/drivers/sqlite/index.js, src/migrations.js, test/integration/custom.test.js, test/integration/mysql.test.js, test/integration/suite/data_types.test.js, test/integration/suite/migrations.test.js, test/unit/drivers/sqlite/index.test.js, test/unit/expr_formatter.test.js, test/unit/spell.test.js
```js
Post.where('createdAt > ?', '2022-11-03')
```
should generate following SQL
```sql
-- correct
SELECT * FROM articles WHERE gmt_create > '2022-11-03 00:00:00.000'
```
rather than 
```sql
-- wrong
SELECT * FROM articles WHERE gmt_create > '2022-11-02 16:00:00.000'
```
=> fix: date strings should be parsed with system time zone considered

src/data_types.ts, src/spell.d.ts, src/types/abstract_bone.d.ts, test/integration/suite/data_types.test.js, test/types/querying.test.ts, test/types/spell.test.ts, test/unit/bone.test.js
=> fix: `cast/uncast` STRING and TEXT with non-string type value, and some type definitions

index.d.ts, src/adapters/sequelize.d.ts, src/types/abstract_bone.d.ts, src/types/common.d.ts, test/types/querying.test.ts
=> fix: fix Bone.create(values) params type definitions

src/adapters/sequelize.d.ts, test/types/sequelize.test.ts
=> fix: types for findAndCountAll

src/adapters/sequelize.d.ts, src/collection.js, src/spell.d.ts, src/types/abstract_bone.d.ts, src/types/common.d.ts, test/types/basics.test.ts, test/types/sequelize.test.ts, test/types/spell.test.ts, test/unit/bone.test.js
=> fix: adapt facebook hermes or metro bundler for loop

src/bone.js, src/drivers/abstract/spellbook.js, src/spell.js, src/types/abstract_bone.d.ts, test/integration/suite/associations.test.js, test/unit/drivers/abstract/spellbook.test.js, test/unit/spell.test.js
=> feat: optimize join query parsing fix #378

src/data_types.ts
> Operator '>' cannot be applied to types 'string | number' and 'number'.
=> fix: avoid ts type detect error

src/drivers/index.d.ts
=> fix: typo DataType for AbstractDriver

src/bone.js
=> fix: don't overwrite primaryKey with LAST_INSERT_ID() if exists

.eslintrc.js, index.d.ts, src/adapters/sequelize.d.ts, src/spell.d.ts, test/types/sequelize.test.ts
=> chore: export { WhereConditions }

src/spell.d.ts, test/types/spell.test.ts
=> fix: fix scope type definitions

package.json, src/data_types.ts, test/unit/data_types.test.js
=> feat: ignore json parse error if jsonType.ignoreError is positive

package.json, src/adapters/sequelize.d.ts, src/bone.d.ts, src/hint.d.ts, src/index.d.ts, src/raw.ts
=> fix: export more ts type definitions

.github/workflows/nodejs.yml, src/drivers/sqljs/sqljs-connection.ts, src/types/common.d.ts, test/types/decorators.test.ts
When using the built-in validators min and max like this
````ts
@Column({
type: DataTypes.TINYINT,
validate: {
min: 0,
max: 10,
},
})
count: number;
````
It will trigger a TypeScript type error: `Type 'number' is not assignable to type 'Validator'`.
Complete the type BaseValidateArgs
=> fix: type error in validate when using min max

src/expr.js, src/expr_formatter.js, test/unit/expr.test.js, test/unit/expr_formatter.test.js
It looks like the performance of querying properties in native JSON data type in MySQL can be boosted with specific index, as long as the index is created with JSON_VALUE(field, path RETURNING type) that casts the property value to certain type.
To enable this optimization, the expression parser and formatter in Leoric needs to be updated, hence proposed this pr.
- https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-21.html#mysqld-8-0-21-json
- https://dev.mysql.com/doc/refman/8.0/en/json-search-functions.html#function_json-value
=> feat: support JSON_VALUE(j, '$.a' RETURNING CHAR(50))

.github/workflows/nodejs.yml, .github/workflows/npmpublish.yml, src/realm/base.js, test/unit/raw.test.js, test/unit/realm.test.js
leoric models depends on several static attributes of parent class (namely `Bone`), such as driver, options, and models. For single data source scenarios, this won't be a problem. But if multiple data sources where introduced, like the midway leoric component, or the egg orm plugin, this could be problematic. 
```js
class Post extends Bone {}
```
Post model extends from the base class, but the actual base class in the realm will be changed to a subclass of Bone, Hence make Post unable to reference the meta attributes correctly.
=> fix: meta attributes should still be available if subclass-ed

docs/assets/css/style.scss, docs/setup/midway.md, docs/zh/setup/midway.md
=> docs: elaborate on midway leoric component usage

src/bone.js, test/integration/suite/json.test.js
=> fix: escape single quotation mark in json merge values

package.json, src/bone.js, src/expr.js, src/types/abstract_bone.d.ts, test/integration/suite/json.test.js, test/start.sh, test/unit/expr.test.js
=> fix: jsonMerge with complex json literals

src/bone.js, test/integration/suite/json.test.js
=> fix: should still be able to jsonMerge() even if currently null

src/bone.js, test/integration/suite/json.test.js
```typescript
class Post {
@Column(DataTypes.JSONB)
extra: Record<string, unknown>
}
const [post] = await Post.select('extra', "JSON_EXTRACT(extra, '$.foo') AS foo");
console.log(typeof post.extra); // expected "object", actually got "string"
=> fix: object results should have attribute values casted as well
